[general]
import = [
   "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "Iosevka", style = "Regular" }

