#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

dunst &

$HOME/.config/polybar/launch.sh

if [[ $(xrandr -q | grep 'DP-2 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1200 --output DP-2 --mode 1920x1080 --above eDP-1
fi

bspc monitor eDP-1 -d I II III IV V
bspc monitor DP-2 -d EXT
bspc wm --reorder-monitors eDP-1 DP-2

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
